### ISSUE TITLE
Is there a way to automatically get all pages?

### ISSUE THREAD

**Issue by swduncan** [ample/surveygizmo#1]
It seems that the functions as-is only get the first page of data. So, if you have 70 surveys and get a list of surveys, you'll only get the first 70. 

Is there any way to automatically get all the data?

**Comment by uhlenbrock** [comment]
Steve, I just pushed a change to surveys which allows all query string parameters, and not just filters. According to the [SG API](http://developer.surveygizmo.com/resources/filtering-and-browsing-results/), you can request up to 500 records per page.

```
Surveygizmo.surveys(:resultsperpage => 500)
```

After 500, you'll need to implement paging, with a `:page => 2` parameter.

**Comment by swduncan** [comment]
Howdy,

I can't seem to get the paging to work. How does the formatted_filters method convert :resultsperpage into something SG understands?

Steve Duncan
+1 414-839-5572

**Comment by uhlenbrock** [comment]
As of 39bf457c48a50809a193c5ac57423839751ea5b8, formatted_filters is no longer used on surveys.
